Этап 1 дипломной работы
valentin32k/java-explore-with-me pull request #3
Opened 2023-06-23 20:32 UTC by valentin32k

2023-06-24 21:17 UTC, Donald522 requested changes
Привет!

Все хорошо, немного покомментил

2023-06-24 21:17 UTC, Donald522 commented on stats-service/server/src/main/java/ru/practicum/statsservice/server/HitController.java
> +        Hit hit = new Hit();
Давай конвертацию унесем в класс маппер

2023-06-24 21:17 UTC, Donald522 commented on stats-service/server/src/main/java/ru/practicum/statsservice/server/HitRepository.java
> +            "order by count (h.id) desc")
Лучше писать count(*) в таких случаях, это быстрее работает

2023-06-24 21:17 UTC, Donald522 commented on stats-service/server/src/main/resources/schema.sql
> +    timestamp TIMESTAMP WITHOUT TIME ZONE                         NOT NULL
Индекс надо добавить

2023-06-25 12:19 UTC, valentin32k commented on stats-service/server/src/main/java/ru/practicum/statsservice/server/HitRepository.java
> +            "order by count (h.id) desc")
Исправил

2023-06-25 12:50 UTC, valentin32k commented on stats-service/server/src/main/java/ru/practicum/statsservice/server/HitController.java
> +        Hit hit = new Hit();
Понимаю, что конвертация классов - это скорей ответственность проекта dto, но как сделать там маппер я не сообразил. Мапперу нужен класс Hit из проекта server, а серверу нужны классы InputHitDto и OutputHitDto. В результате чего получается перекрестная ссылка, поэтому маппер создал в проекте сервера.

2023-06-25 12:53 UTC, valentin32k commented on stats-service/server/src/main/resources/schema.sql
> +    timestamp TIMESTAMP WITHOUT TIME ZONE                         NOT NULL
Тут не совсем понял какого индекса не хватает?

2023-06-25 16:24 UTC, Donald522 commented on stats-service/server/src/main/resources/schema.sql
> +    timestamp TIMESTAMP WITHOUT TIME ZONE                         NOT NULL
Индексы нужны на колонки, по которым есть условия. В данном случае это колонка timestamp

2023-06-25 16:30 UTC, Donald522 commented on stats-service/server/src/main/java/ru/practicum/statsservice/server/HitController.java
> +        Hit hit = new Hit();
Ты правильно сделал. Маппер это не ответственность модуля dto, а ответственность сервера, тк только сервер знает схему своей БД.

2023-06-25 16:31 UTC, Donald522 approved these changes
Привет, в след работе добавь индекс, пожалуйста.

2023-06-25 18:01 UTC, merged