Этап 2 дипломной работы
valentin32k/java-explore-with-me pull request #4
Opened 2023-07-18 19:14 UTC by valentin32k

2023-07-19 20:17 UTC, Donald522 requested changes
Привет!

Все здорово, но несколько замечаний написал.

2023-07-19 20:17 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/compilations/Compilation.java
> +    private List<Long> eventIds;
Не очень наглядно будет.
В таблицы постоянно приходится смотреть глазами. В этом смысла таблицы маппингов - так себе.

Я бы добавил тут колонку с id событий

2023-07-19 20:17 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/compilations/CompilationServiceImpl.java
> +        compilation.setEvents(getCompilationEvents(compId));
В чем смысл делать таблицу маппинга, чтобы все равно делать 2 запроса?

Таблица маппинга хороша тем, что позволяет достать все 1 запросом с помощью джойнов
Но в остальном она всем плоха. Сделать 2 запроса наверное даже наименьшее из зол в этом случае.

Я бы хранил в таблице компиляций списком id событий, а вторым запросом по этим id доставал события. А таблицу маппинга удалил бы

2023-07-19 20:17 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/events/EventRepository.java
> +    Page<Event> searchPublicEvents(String text,
Насколько я понимаю, это один из самых используемых запросов, тк он доступен даже не зарегистрированным пользователям.

Тут нужно уделить особое внимание его производительности. Не увидел на таблице events ни одного индекса. Все http запросы будут падать по таймаутам.

2023-07-22 11:58 UTC, valentin32k commented on main-service/pom.xml
> +            <groupId>com.h2database</groupId>
Не используется. Убрал

2023-07-22 13:37 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/categories/Category.java
> +@Getter
Исправил, но их все равно больше чем полей получается)

2023-07-23 18:38 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/compilations/Compilation.java
> +    private List<Long> eventIds;
Исправил

2023-07-23 18:40 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/compilations/CompilationServiceImpl.java
> +        compilation.setEvents(getCompilationEvents(compId));
Исправил, стало намного удобней

2023-07-23 19:02 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/events/EventRepository.java
> +    Page<Event> searchPublicEvents(String text,
Добавил индексы для полей, используемых в публичных методах. Возможно, имело смысл индексировать что-то еще?

2023-07-24 07:27 UTC, Donald522 commented on main-service/pom.xml
> +            <groupId>com.h2database</groupId>
Это только кажется. Ее синтаксис и возможности далеки от постгреса (да и от любой настоящей базы)
Так что на нее не стоит ориентироваться.

2023-07-24 07:32 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/events/EventRepository.java
> +    Page<Event> searchPublicEvents(String text,
Возможно и имеет, а может и нет.
Индекс это всегда компромисс, а не панацея. Он занимает место на диске и замедляет запись (тк при записи надо обновить каждый индекс, который затронут этой записью)

Чтобы понять, какие индексы нужны, нужно смотреть какие запросы часто используются и оптимизировать конкретно их. Оптимизация в вакууме невозможна.

Я написал комментарий скорее с целью дать понять, что об этом надо задумываться, чем с целью сделать идеально прямо сейчас в этой работе.

2023-07-24 07:33 UTC, Donald522 approved these changes

2023-07-24 18:05 UTC, merged