feat: Добавить комментарии
valentin32k/java-explore-with-me pull request #5
Opened 2023-07-30 22:21 UTC by valentin32k

2023-07-31 20:31 UTC, Donald522 requested changes
Привет!

Написал замечания.

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/AdminCommentController.java
> +    public List<CommentDto> getComments(@PathVariable long adminId,
А почему логин не через заголовки передается?
У нас администратор - это не ресурс. Поэтому путь /admin не выглядит правильным

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/AdminCommentController.java
> +                                        @RequestParam(defaultValue = "") List<Long> events,
Как будет использоваться этот метод?

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/PrivateCommentController.java
> +                                                 @RequestParam(defaultValue = "1970-01-01 00:00:01") Timestamp rangeStart,
А зачем тут дефолтные значения?
Можно же при отсутствии значений просто не делать условие в запросе к бд

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/PrivateCommentController.java
> +    public List<CommentDto> getCommentsByEventId(@PathVariable long userId,
Почему этот метод в приватном контроллере? Незареганые пользователи не могут читать комментарии?

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/PrivateCommentController.java
> +@RequestMapping(path = "/users/{userId}/events/{eventId}/comment")
userId надо передавать через заголовок
в данном случае user это не ресурс. Ресурс здесь комментарии

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +        if (comment.getAuthor().getId() != userId && !isRemovedByAdmin) {
Эту проверку нужно сделать на уровне запроса
Не надо делать 2 запроса в БД для удаления сущности

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +        updatedComment.setUpdated(Timestamp.valueOf(LocalDateTime.now()));
Тут получается будет хранится только последний кто обновил?
Я думаю тогда надо поле назвать соответственно - lastUpdatedAt, lastUpdatedBy

В идеале вообще хранить всю историю обновления, хотя наверное в случае с комментариями это не так уж и надо

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +                .findById(userId)
В чем смысл этих проверок при наличии foreign key?

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +                        Timestamp.valueOf(LocalDateTime.now()),
В now советую всегда передавать clock

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/resources/schema.sql
> +    text       VARCHAR(4095)                                       NOT NULL,
Почему 4095?
Если мы ограничиваем в БД, то почему не ограничиваем на уровне контроллера?

2023-07-31 20:31 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +        PageRequest request = PageRequest.of(from / size, size, Sort.by(Sort.Direction.DESC, "created"));
Сортировка по неиденксированному полю приведет к полному сканированию таблицы и соотв плохо производительности

2023-08-02 19:18 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/AdminCommentController.java
> +    public List<CommentDto> getComments(@PathVariable long adminId,
Перенес логин пользователя в заголовки. Слова /admin в адресе тоже не должно быть или его можно оставить? Мне кажется, что со словом admin будет удобней: во-первых, понятно к какому контроллеру адресован запрос, во-вторых, такой же принцип используется для других контроллеров приложения, такая адресация будет однообразна

2023-08-02 19:20 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/AdminCommentController.java
> +                                        @RequestParam(defaultValue = "") List<Long> events,
Я думал, что с его помощью администраторы будут просматривать комментарии к событиям, фильтруя их. Но, наверное, запросов из контроллера обычного пользователя им будет достаточно, поэтому метод убрал

2023-08-02 19:22 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/PrivateCommentController.java
> +                                                 @RequestParam(defaultValue = "1970-01-01 00:00:01") Timestamp rangeStart,
Все исправил.

2023-08-02 19:25 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/PrivateCommentController.java
> +    public List<CommentDto> getCommentsByEventId(@PathVariable long userId,
Мне казалось, что незарегистрированные пользователи не должны иметь возможность читать комментарии. Видимо ошибался. Перенес метод в публичный контроллер

2023-08-02 19:26 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/PrivateCommentController.java
> +@RequestMapping(path = "/users/{userId}/events/{eventId}/comment")
Исправил

2023-08-02 19:26 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +        if (comment.getAuthor().getId() != userId && !isRemovedByAdmin) {
Исправил

2023-08-02 19:27 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +        updatedComment.setUpdated(Timestamp.valueOf(LocalDateTime.now()));
Исправил

2023-08-02 19:27 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +                .findById(userId)
Смысла нет. Проверки убрал

2023-08-02 19:27 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +                        Timestamp.valueOf(LocalDateTime.now()),
Исправил

2023-08-02 19:36 UTC, valentin32k commented on main-service/src/main/resources/schema.sql
> +    text       VARCHAR(4095)                                       NOT NULL,
Мне кажется, что размер комментария должен быть ограничен. С размером ограничения мог ошибиться, потому что значение взял с потолка. Размер текста мы ограничиваем аннотацией @Size в классе NewCommentDto, а потом в методах create и update, описанных в классе PrivateCommentController, аннотацией @Valid проверяем соответствие размера текста требуемым ограничениям. Или я не правильно понял вопрос? Оо

2023-08-02 19:37 UTC, valentin32k commented on main-service/src/main/java/ru/practicum/mainservice/comments/CommentServiceImpl.java
> +        PageRequest request = PageRequest.of(from / size, size, Sort.by(Sort.Direction.DESC, "created"));
Добавил индекс

2023-08-03 18:26 UTC, Donald522 commented on main-service/src/main/java/ru/practicum/mainservice/comments/PrivateCommentController.java
> +    public List<CommentDto> getCommentsByEventId(@PathVariable long userId,
Тут же нет правильного и неправильного ответа (как это часто бывает)
Это твое решение. твой дизайн, я просто спрашиваю то, как ты это видишь и почему принял то или иное решение.

2023-08-03 18:28 UTC, Donald522 commented on main-service/src/main/resources/schema.sql
> +    text       VARCHAR(4095)                                       NOT NULL,
Да, извини, я посмотрел не в ту модельку (посмотрел в CommentDto)
То, что надо ограничивать размер комментария - точно надо, тут ты прав.
Интересно было откуда значение 4095

2023-08-03 18:29 UTC, Donald522 approved these changes
Привет!

Принимается

2023-08-04 08:44 UTC, merged